### ISSUE TITLE
Multiple axis example

### ISSUE THREAD

**Issue by 7Pass** [d3fc/d3fc#1017]
I'm trying to create D3.js chart with right Y axis (http://bl.ocks.org/d3noob/e34791a32a54e015f57d) and get stuck.

`cartesian` is very convenient for creating standard chart with X and Y axis, but it does not seems to support adding the right Y axis. Is there any way I can decorate `cartesian` to add right Y axis, or do I need to recreate functionalities of `cartesian` myself in order to have right Y axis?

**Comment by chrisprice** [comment]
Whilst you could decorate in to `cartesian` a second y axis, it isn't very well suited to it because it's fundamentally based around there only being one x and one y scale which are passed to each series (I'm assuming you want two distinct y scales).

I'd recommend either duplicating the code of `cartesian` and extending it to support a third scale/axis or alternatively, if you don't need the labels, I'd build it from scratch making use of the [axis series](https://github.com/ScottLogic/d3fc/blob/master/src/series/axis.js) and laying out the elements manually rather than using `layout` (which is overkill for simple charts).

**Comment by gabidi** [comment]
@ColinEberhardt  in reference to the excellent article you wrote on your blog:
http://blog.scottlogic.com/2015/07/08/yahoo-finance-chart.html

Specifically to Dual axis creation (for Volume bars). The code quoted below no longer seems to work with V4's re-write, would you possibly be able to give some guidance on how to replicate the dual Y-axis feature within the new code base ? Thank you so much

```js
  var container = d3.select('#time-series');
  var volumeContainer = container.selectAll('g.volume')
        .data([data]);
  volumeContainer.enter()
      .append('g')
      .attr({
          'class': 'volume',
      })
      .layout({
          position: 'absolute',
          top: 150,
          bottom: xAxisHeight,
          right: yAxisWidth,
          left: 0
      });

  var layout = fc.layout();
  container.layout();
```

**Comment by chrisprice** [comment]
N.B. There's an example of using dual-axes in the d3fc-element package - 

![image](https://user-images.githubusercontent.com/433457/44574546-99567500-a781-11e8-8acd-a82dbeb5de42.png)

https://github.com/d3fc/d3fc/blob/master/packages/d3fc-element/examples/dual-axes.html

**Comment by ColinEberhardt** [comment]
documented here: https://github.com/d3fc/d3fc/tree/master/packages/d3fc-chart#adding-a-second-axis
