### ISSUE TITLE
Small gap appears between gridlines and axis ticks on window resize.

### ISSUE THREAD

**Issue by j-n-white** [d3fc/d3fc#1067]
I've created a small project that reproduces this issue: https://github.com/j-n-white/gridline-rendering-issue-example

**Comment by chrisprice** [comment]
```
$ react-scripts start
Could not find a required file.
  Name: index.html
  Searched in: /Users/chris/gridline-rendering-issue-example/public
error Command failed with exit code 1.
```

**Comment by chrisprice** [comment]
Fixed the above by [grabbing the default](https://raw.githubusercontent.com/facebookincubator/create-react-app/master/packages/react-scripts/template/public/index.html)

```
W
Failed to compile.

Error in ./src/index.js
Module not found: ./main in /Users/chris/gridline-rendering-issue-example/src

 @ ./src/index.js 4:0-17

```

**Comment by chrisprice** [comment]
Using a global typescript install and running `tsc` fixed the above.

Can't reproduce on Chrome 57 on Mac, trying BrowserStack Win7 Chrome 57 instance.

**Comment by chrisprice** [comment]
I can reproduce by making the window narrower. Changing the height doesn't seem to trigger it.

Interestingly the dev tools device toolbar doesn't trigger the behaviour either when clicking between the settings or manually setting a smaller width.

**Comment by chrisprice** [comment]
The problem seems to be caused by the browser thinking a horizontal scrollbar is needed on the body at the time of measuring. Need to think over why we've not seen this before and how best to fix or workaround it.

**Comment by j-n-white** [comment]
That is encouraging progress. Thanks for investigating this.

**Comment by chriswilty** [comment]
So, it turns out the issue is specific to windows OS, and is due (correct me if I'm wrong, @chrisprice ) to the browser attempting to initally render a horizontal scrollbar when not needed, then presumably removing it before the final rendering, but by that stage the % heights for our container rows have already been calculated (ultimately, relative to the available page height) and the svg rendering triggered, and when the scrollbar is subsequently removed it results in a small amount of extra space being allocated to the container rows but not to the svgs, hence a small gap appears between chart and axis. Drag-resizing the window causes a re-render which fixes the gap (this time, no horizontal scrollbar is attempted), although maximizing/restoring the window seems again to trigger this weird horizontal scrollbar thing.

I may not have explained that very well, but it's a weird thing which seems to defy a good explanation!

Anyhow, the fix for us was to apply 
`overflow-x: hidden`
to the body. This worked fine for our SPA, but if horizontal scrolling is something your app relies on, then obvs this won't work :grimacing:

**Comment by chrisprice** [comment]
Something like that 😄 

I'd still love to know why the browser thought that it was wide enough to require a scrollbar. The only thing that had any fixed width was the svg which itself was positioned absolutely and should therefore not have contributed to the layout.

**Comment by ryanggrey** [comment]
PR https://github.com/d3fc/d3fc-chart/pull/28

**Comment by ryanggrey** [comment]
@j-n-white @chriswilty Are you happy for this issue to be closed or would you like to test changes against your app first?

**Comment by chriswilty** [comment]
@ryanggrey Happy for it to be closed :+1:

At some stage it will get tested against Gridwatch, but for now our workaround is sufficient. Thanks!

**Comment by ryanggrey** [comment]
@chrisprice please close
