### ISSUE TITLE
how to increase yAxis width?

### ISSUE THREAD

**Issue by eesur** [d3fc/d3fc#1081]
Sorry if missing something obvious, but don't see how I can increase the yAxis width so it displays larger numbers that in turn don't overlap with the yAxis label

I've [forked](https://codepen.io/eesur/pen/eEwNda) the [Building A Chart](https://d3fc.io/introduction/building-a-chart.html) example: https://codepen.io/eesur/pen/eEwNda

<img width="633" alt="screen shot 2017-09-07 at 16 06 27" src="https://user-images.githubusercontent.com/1597761/30170275-90d17a42-93e6-11e7-964f-a264466d7007.png">

I've tried working it out via the docs and looked at [d3fc-element](https://github.com/d3fc/d3fc-element) and  tried via the decorate and via css but it causes the `plot-area` to become disproportionate

Thanks for all the awesome work/sharing of these super useful components!

**Comment by ColinEberhardt** [comment]
The d3fc cartesian chart component constructs a chart from a number of elements, with the overall layout achieved using CSS flexbox. Here's the basic layout:

```
<d3fc-group class="cartesian-chart" style="display: flex; height: 100%; width: 100%; flex-direction: column; overflow: hidden" auto-resize="">
  <div class="chart-label" style="height: 2em; line-height: 2em; text-align: center; margin-right: 4em">2015 Cumulative Sales</div>
  <div style="flex: 1; display: flex; flex-direction: column; padding-left: 1em">
    <div style="flex: 1; display: flex; flex-direction: row">
      <d3fc-svg class="plot-area" style="flex: 1"></d3fc-svg>
      <d3fc-svg class="y-axis" style="width: 3em;"></d3fc-svg>
      <div style="width: 1em; display: flex; align-items: center; justify-content: center">
        <div class="y-axis-label" style="transform: rotate(-90deg)">Sales (millions)</div>
      </div>
    </div>
    <d3fc-svg class="x-axis" style="height: 2em; margin-right: 4em"></d3fc-svg>
    <div class="x-axis-label" style="height: 1em; line-height: 1em; text-align: center; margin-right: 4em"></div>
  </div>
</d3fc-group>
```

Notice that the styling is all inline, this is so that d3fc can be distributed as pure JavaScript, with no associated CSS (just like D3!).

To make the y axis wider, you'll need to change the `width` CSS property of the `d3fc-svg` element that has the `y-axis` class.

There are a couple of ways you could do this:

1. Using the decorate pattern ...

~~~
var chart = fc.chartSvgCartesian(
        d3.scaleBand(),
        d3.scaleLinear())
    .chartLabel("2015 Cumulative Sales")
    ....
    .decorate(sel => {
        sel.enter()
           .select('.y-axis')
            .style('width', '10em');
    });
~~~

When the chart is rendered the decorate function is invoked with the selection that is used to create the chart. Here we access the enter selection (which is invoked only once, when the chart is initially drawn), and change the required CSS attribute.

Because the chart is constructed from standard HTML elements, the rest of the layout adjusts accordingly.

2. Using CSS

~~~
.chart .y-axis {
    width: 10em !important;
}
~~~

You can of course also change the width via CSS, but because the styles are inline, you'll need a bang-important to increase the specificity.

> Thanks for all the awesome work/sharing of these super useful components!

Glad you like them!

**Comment by eesur** [comment]
Thanks Colin, it works great when `.yOrient('right')`:

<img width="968" alt="screen shot 2017-09-08 at 09 05 51" src="https://user-images.githubusercontent.com/1597761/30202113-2f3419ae-9475-11e7-89c4-c5a788774f63.png">

but pushes the chart across when `.yOrient('left')`

<img width="943" alt="screen shot 2017-09-08 at 09 06 38" src="https://user-images.githubusercontent.com/1597761/30202154-58e73fe2-9475-11e7-98c5-65f65198d676.png">

I've updated the example: https://codepen.io/eesur/pen/eEwNda

**Comment by ColinEberhardt** [comment]
Ah, the problem here is that the x axis has a left margin which is equal to the y axis and label width. If you change the y axis width, you need to update the left margin too.

```
   .decorate(sel => {
        sel.enter()
           .select('.y-axis')
            .style('width', '10em')
        sel.enter()
           .select('.x-axis')
           .style('margin-left', '11em')
    })
```

It's more luck that you don't need to do this for a right aligned axis ;-)

I think this would be much easier to configure if the cartesian chart component used grid layout, rather than flexbox. With a grid there isn't such a coupling between the properties of each element.

It looks like there is decent support now:

http://caniuse.com/#feat=css-grid

@eesur if you're interested in trying this out - we'd love a contribution!

**Comment by eesur** [comment]
thank you, much appreciated! it makes sense now you you showed me :) —grid layout sounds  a good shout; will look into it :)
