### ISSUE TITLE
candlestick chart example

### ISSUE THREAD

**Issue by dormadekhin** [d3fc/d3fc#1102]
is there an example of using a candlestick chart with zoom, crosshair  and navigator chart with d3fc brush?
Thank you

**Comment by chrisprice** [comment]
> is there an example of how to use a crosshair with сandlestick series?
> in the documentation, only an example for a linear chart

**Comment by gtzilla** [comment]
I've been working on building something similar to this request. It took a very long time to uncover the 'magic' `scaleLinear.invert` and scale discontinuous time, invert, which you will need to put together a crosshair. Google turns up a very old yahoo finance chart example that iirc @ColinEberhardt may have written. I've looked at a lot of different samples recently.  In short, after much effort I wasn't able to find a single complete example.

I'm going to share the sources I've used to both see if there are better variants as well in hopes of moving towards a functional example of this feature set.

Being able to go from x,y to appropriate scale value that includes time requires the `invert` method here. https://github.com/d3fc/d3fc-discontinuous-scale#scalediscontinuous 

Candlesticks are so simple with d3fc it's almost criminal.  Candlesticks / ohlc with streaming data can be found here: https://bl.ocks.org/ColinEberhardt/ab7805a9a7af9717e86adc1656fa98d9

And a basic crosshair example works here. Though google has several versions that have various implementation versions. https://bl.ocks.org/ColinEberhardt/7afb58d94428c28c960d243b5299f4d4

For non technical project reasons, we are updating the regular HTML DOM outside of the chart on pointer event. For now, an external DOM template library injects output from the crosshair into the DOM. I am using the 'point' event. 

What this is the best place to update DOM external to d3fc from d3fc events? I also have-to-call a `render` method on the `point` event and redraw the d3fc nodes to handle the movement of the crosshair. d3fc appears to call requestAnimation frame, however.  My concern, tying a separate DOM update and re-paint/re-flow from 'point' would be similar to updating from on-scroll. I'm trying to push my DOM update to the next tick with a `setTimeout(func,1);` as a result. But it seems like this isn't an uncommon requirement. 

```
var pointer = fc.pointer()
                  .on('point', function(event){
                       // update the dom, render the chart again, assign event to obj for ref.
                  })
```

I am working from this brushed example.  https://bl.ocks.org/ColinEberhardt/000b1721b69868f1ce5d It's last on my list to-do because it will require an extended data set from my app. I've assumed brushed example contains zoom / backward / forward time panning. Definitely need to explore to whether it can handle infinite data and properly load / unload data, however.
