### ISSUE TITLE
d3fc-canvas register Error if included as content_script vr 13.1.1

### ISSUE THREAD

**Issue by gtzilla** [d3fc/d3fc#1187]
The browser Google Chrome (v68 official) reports an error when including `d3fc.min.js` as part of a Google Chrome Extension content script.

Specifically, loading d3fc.min.js (not invoke, just add as a script) results in an error message:  
```
d3fc.min.js:3 Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'd3fc-canvas'. Elements cannot be registered from extensions.
```

I haven't, intentionally, been adding d3fc-canvas. My application is limited to SVG in the near term.  I believe this error may originate from here https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/src/canvas/cartesian.js 

I am linking to a small demo project created to demonstrate the error. https://github.com/gtzilla/d3fc_canvas_chrome_error 

Also attaching a screenshot of this opportunity since it requires a specific environment.

![screen shot 2018-09-02 at 9 53 18 am](https://user-images.githubusercontent.com/185538/44956846-635b7400-ae98-11e8-8a85-a120ab253a74.png)

**Comment by chrisprice** [comment]
The library (when used as a bundle) requires a working custom element API. The code causing the error can be found in [d3fc-element](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-element/index.js). Unfortunately for your situation, this package is required by d3fc-chart. 

I think you have a couple of options:

Use your extension script to load d3fc as another script into the document. 

Use the individual packages rather than the bundle. However this approach still will not permit the use of d3fc-chart.
