### ISSUE TITLE
Perfomance of D3FC with realtime HF data

### ISSUE THREAD

**Issue by serzhiio** [d3fc/d3fc#1203]
Hi i'm testing d3fc with realtime orderbook data which updates every 15-50ms.
What is the best practice for such data? How to turn of any transitions, durations and so on?
Canvas or SVG? :)

**Comment by serzhiio** [comment]
And is there a chance to not redraw full chart every time data comes?

**Comment by serzhiio** [comment]
BTW outstanding work!!! Thank you!!!

**Comment by ColinEberhardt** [comment]
Hi - a few quick answers for you ...

d3fc doesn’t really have any transitions - we lead that for the other, more flashy, charting libraries!

You asked about not redrawing the full chart - this is actually a built in feature of D3 data joins. It will only update the DOM when the bound data has changed. This way you can tell a chart component to redraw, but only the parts that have changed will be redrawn.

Regarding performance, canvas is typically a lot faster than SVG if you have a lot of data.

**Comment by serzhiio** [comment]
Thx for explanations, but related to time scale, how to control particular
time span showing/drawing? If i want to load only 30min of data (not exact
amount of points)

... and if we have **data.join()** we should have **data.remove()**, no?

сб, 20 окт. 2018 г., 11:39 Colin Eberhardt <notifications@github.com>:

**Comment by serzhiio** [comment]
30m of realtime data cause constant [viaolation] messages
![requestredraw](https://user-images.githubusercontent.com/10449591/47322680-8a951d00-d661-11e8-803a-09dba421bdaa.jpg)
```
        d3.select('#plot-area')
          .on('draw', (d, i, nodes) => {
            const context = nodes[i].children[0].getContext('2d')
            priceAskSeries.context(context)
            priceBidSeries.context(context)
            volumeSeries.context(context)
            priceAskSeries(data)
            priceBidSeries(data)
            volumeSeries(data)
          })
        container.node().requestRedraw()
```
_maybe there is more efficient way to update chart?_

**Comment by serzhiio** [comment]
Looks like most of cpu consumption ate by BAR rendering:
![bar-issue](https://user-images.githubusercontent.com/10449591/47322958-99c89a80-d662-11e8-9a69-f9674412dbfd.jpg)

**Comment by chrisprice** [comment]
If I've understood your description correctly, ’data’ would be expected to contain approximately 10k points. Rendering that much data is likely to require some performance tuning. 

Fundamentally you need the code to do less work. You can do this by-

* Ensuring you're only rendering the visible data
* Simplifying the data using some form of smoothing/merging technique. ’d3fc-sample’ may or may not be appropriate for this. 
* Dropping down to using the path generators from ’d3fc-shape’ directly to optimise their use for performance rather than flexibility. At this stage typical canvas rendering optimisation techniques can be used (e.g. add many segments to a path and then stroke, don't change context settings unnecessarily etc.)
* Only rendering the updated data. In the case of canvas this will require decorating in a second hot ’d3fc-canvas’ for updates and some manual bookkeeping to track when it's appropriate to only update that canvas. 

Unfortunately these optimisations tend to be quite use case specific. They trade flexibility for performance where d3fc typically chooses flexibility.

**Comment by serzhiio** [comment]
The case is really specific its true. But imo good instrument for data partial update will not hurt anybody :)
And i still cant understand how to render new data and delete old not redrawing full canvas? Could you explain me please?
