### ISSUE TITLE
Is it possible to customize the d3fc-label-layout?

### ISSUE THREAD

**Issue by geohuz** [d3fc/d3fc#1214]
So in label layout we have many black dot being draw on the map, is it possible to customize them? For example, disable the dot, or colorizing them?

**Comment by ColinEberhardt** [comment]
The easiest way to do this is via CSS. If you are using the `layoutTextLabel` component, as per this example: https://bl.ocks.org/ColinEberhardt/raw/389c76c6a544af9f0cab/, you will see that the dots are rendered as `circle` elements:

```
<g class="label">
   <rect width="65.921875" height="20"></rect>
   <circle r="2" cx="0" cy="0"></circle>
   <text dy="0.9em" transform="translate(2, 2)">Aberdeen</text>
</g>
```

In order to change them to red dots, the following CSS will do the trick:

```
.label circle {
    fill: red;
}
```

If however, you want to change the fill colour based on some property of the data, you will need to use the [decorate pattern](https://d3fc.io/introduction/decorate-pattern.html)

**Comment by geohuz** [comment]
@ColinEberhardt Thanks for the solution!
