### ISSUE TITLE
screenshots are broken on npm

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1240]
https://www.npmjs.com/package/@d3fc/d3fc-series

![image](https://user-images.githubusercontent.com/1098110/54133391-e93f1580-440d-11e9-81d4-b067ab650de7.png)

**Comment by andy-lee-eng** [comment]
@ColinEberhardt the only way I can find to get the links to work in both npm and GitHub is by using links relative to the root repo, so like this:

```html
<tr>
  <td><a href="#boxplot"><img src="/packages/d3fc-series/screenshots/boxplot.png"/></a></td>

  <td><a href="#candlestick"><img src="/packages/d3fc-series/screenshots/candlestick.png"/></a></td>

  <td><a href="#line"><img src="/packages/d3fc-series/screenshots/line.png"/></a></td>
</tr>
```

Currently we only use links relative to the ReadMe, e.g. `screenshots/boxplot.png`

This requires changing all the links in all the ReadMes, and we'll also need to "fix" the links when generating the documentation (which is an easy fix).

The downside is that developers will not be able to see the images when writing and previewing the ReadMe (like you can at the moment, e.g. in VS Code). Also, developers would need to remember to use the long version of the link.

**Comment by andy-lee-eng** [comment]
I've tried experimenting with changing the links in the `package.json` files for the individual packages, but it doesn't help. There's even a `directory` option that we don't currently use, specifically for mono-repos, but it doesn't seem to help with the relative paths to images.

i.e. 
```
  "homepage": "https://github.com/d3fc/d3fc",
  "repository": {
    "type": "git",
    "url": "https://github.com/d3fc/d3fc",
    "directory": "packages/d3fc-series"
  },
```

The "homepage" and "repository" settings above do affect the "homepage" and "repository" links on the npm page, which currently point to the root repo rather than the package, so that's something else we could consider changing.
