### ISSUE TITLE
Is there a debug mode?

### ISSUE THREAD

**Issue by danielsokolowski** [d3fc/d3fc#1258]
I have a case where a chart does not work, I persume it's due to the accessor functions getting `undefined` data however no error is thrown or error output to console log, is there some way to enable a debug mode? Or some approach to efficient debugging ? 

Any suggestions are appriciated - Chrome Dev Tools user here.

**Comment by chrisprice** [comment]
Not really no. One debug "trick" I occasionally use is to inspect elements
with chrome dev tools and look for __ prefixed properties which contain the
cached bound data. That might provide some clues but requires a decent
understanding of the chart structure.

If you think it's an accessor problem, you could try overriding the defined
property to be true. That should cause it to throw an error rather than
fail silently.

If you can get something on jsbin demonstrating the problem we can take a
look?

Random feature idea: a no data overlay that offers up internal state in
debug mode and more user friendly in release. (Not sure how we should
detect debug/release)

**Comment by danielsokolowski** [comment]
Thank you.
