### ISSUE TITLE
how to export d3fc chart svg || png?

### ISSUE THREAD

**Issue by RandomFractals** [d3fc/d3fc#1290]
can you even do that with your lib?

my simple data.preview use case scenario: https://github.com/RandomFractals/vscode-data-preview/issues/10

also see how easily it's done in https://github.com/RandomFractals/vscode-vega-viewer

what's your 411 on this, crew? :) 

cc @ColinEberhardt, @chrisprice & @tommclaughlan

**Comment by ColinEberhardt** [comment]
Hi @RandomFractals - as a bit of background, d3fc uses a combination of HTML, CSS, SVG and optionally Canvas in order to render these charts. Therefore, to export to an image, you'll need a technology that an handle all of these technologies

There are a whole host of options available to achieve this:

https://stackoverflow.com/questions/10721884/render-html-to-an-image

I've only really used the 'headless' approach before - some of the screenshots in d3fc use this approach.

**Comment by RandomFractals** [comment]
@ColinEberhardt oh, I am aware of the options as I pointed out in my original query. 

Don't send me to random render html to an image stackoverflow post lol!

I do know how to export SVG || PNG! See here :) https://observablehq.com/@randomfractals/notebook-info

My question **is**: can you provide those interfaces as part of your d3fc charts library?

I just thought it would be handy if you guys did it in your lib for other devs using it.

**Comment by RandomFractals** [comment]
perhaps this could help: https://observablehq.com/@mbostock/saving-svg
