### ISSUE TITLE
How to update classed?

### ISSUE THREAD

**Issue by desmondjim** [d3fc/d3fc#1292]
What i have:
`var textLabel = fc.layoutTextLabel().padding(0).value(function (d) {
        return d.value;
    });
    var label = fc.layoutLabel()
        .size([16,16])
        .position(function (d) {
        return [d.x, d.y];
    })
        .component(textLabel)
        .decorate(function(s) {
            s.enter()
                .each(function(d) {
                    d3.select(this)
                        .select('text')
                        .classed(d.value, true)
                        .text(d.value);
                })
        });`

When i click button to update data, d.value on .text changing, but the same d.value on .classed rest with old value. Why? And how to force it to update?

**Comment by desmondjim** [comment]
i think that the problem in appending new data in decorate function, not replace
how can i replace data?

**Comment by chrisprice** [comment]
You're correct, your decorate function is only targeting new (or entered)
elements. You can fix this by swapping:

s.enter() .each(function(d) { d3.select(this) .select('text')
.classed(d.value, true) .text(d.value); })

For

s.select('text').classed(d.value, true).text(d.value);

This works because the default selection is a merge of the enter and update
selections. There's also no need to use an each as the selection methods
will act on each item in the selection.

Depending on exactly what you're doing the text call may also not be
required.

**Comment by desmondjim** [comment]
> s.select('text').classed(d.value, true).text(d.value);

Unfortunately, in this case d.value is undefined.

**Comment by chrisprice** [comment]
That's what I get for writing code in emails 🙂

You need to swap the references to d.value for d => d.value. In the same
way that selection methods operate on each item, they also accept functions
which are invoked for each item.

**Comment by desmondjim** [comment]
It seems that .classed not accept functions, but .attr('class') do.
https://stackoverflow.com/questions/17452453/how-can-i-use-d3-classed-selection-to-have-name-as-function
Anyways, it's working solution for me, thanks!
