### ISSUE TITLE
scaleMapper.js not working when project compiled using webpack 

### ISSUE THREAD

**Issue by gosthell** [d3fc/d3fc#1490]
The scaleMapper.js use the string representation of the scaler's copy function in order to determine the type of scaler (linear, log, ..). However, the copy function can be different for two similar scalers if a project is compiled using webpack and doesn't use the same d3 module as the one in d3fc-webgl.

`
function() {
   return Object(_continuous__WEBPACK_IMPORTED_MODULE_1__["copy"])(scale, linear());
}
`
`
function() {
    return Object(_continuous__WEBPACK_IMPORTED_MODULE_2__["copy"])(scale, linear());
  }
`

**Comment by gosthell** [comment]
Proposed change
```
import * as d3Scale from 'd3-scale';
import linear from './linear';
import log from './log';
import pow from './pow';

export default scale => {
    let outScale = d3Scale.scaleIdentity();
    let glScale = null;
    const scaleCopyString = scale.copy.toString();

    // compare the stringified 'copy' function of the scale to
    // determine the scale type.
    if (scaleCopyString.search('linear') >= 0) {
        glScale = linear().domain(scale.domain());
    } else if (scaleCopyString.search('log') >= 0) {
        glScale = log()
            .domain(scale.domain())
            .base(scale.base());
    } else if (scaleCopyString.search('pow') >= 0) {
        glScale = pow()
            .domain(scale.domain())
            .exponent(scale.exponent());
    } else if (scaleCopyString.search('calendar') >= 0) {
        glScale = linear().domain(scale.domain());
    } else {
        glScale = linear().domain(scale.range());
        outScale = scale;
    }

    return {
        scale: outScale,
        glScale: glScale
    };
};
```

**Comment by chrisprice** [comment]
Thanks for the report and the suggested fix. It's very frustrating that there isn't a "nice" way to do this and the current technique was the best we could come up with.

One thought that might be root issue of the behaviour your seeing would be 2 slightly different versions of d3-scale being imported. It might be worth checking that there's only 1 version in your `node_modules` tree (i.e. there might be a second version lurking in `node_modules/@d3fc/d3fc-webgl/node_modules`).

My concern with your suggested approach is that minification will most likely rewrite the identifiers that we're matching on. If the above doesn't work I can see 2 remaining options -

* Allow users to register explicit mappings of source scale to something (e.g. gl scale) with `scaleMapper`. If we store them internally in a `WeakMap`, I can't see any issues with lifecycle/memory management.
* Petition `d3-scale` to include some form of identifier. Maybe use a Symbol to reference the component "factory" function. I guess this is unlikely...

**Comment by gosthell** [comment]
Yes this is due to the project using a different version of d3-scale. The posted suggestion works for me for now, as a temporary fix, but indeed it would cause problem in case of minification. Other than what you mentioned, I don't see anything else that could be done.

**Comment by chrisprice** [comment]
FYI we're aware that our [versions are out of date and we'll be updating them all shortly](https://github.com/d3fc/d3fc/issues/1484).

**Comment by chrisprice** [comment]
#1491 has indicated another problem with the existing implementation. We need the escape hatch discussed above i.e. -

Allow global registration of an explicit mapping of an input scale to function accepting the scale and returning a `{ scale, webglScale }` tuple. Store this in a `WeakMap` to prevent memory issues. E.g. -

```js
import { webglScaleLinear, webglScaleMapper } from '@d3fc/d3fc-webgl';

const scale = d3.scaleTime();
webglScaleMapper.register(scale, { scale: (x) => x - 1e6, webglScale: webglScaleLinear });
```

I prefer defining a mapping against an instance, rather than some form of `canHandle` filter function, to prevent global state issues.

However, this approach is going to run into problems with the `isIdentifyScale` checks in `d3fc-series`. We need a way of a scale opting in/out of that check explicitly. N.B. we don't really care if it's an identity scale, it just needs to map back to the value from `scaleMapper` and demonstrate that the result won't change for a given value (until `serries.equals` says it's changed... which seems weak).

**Comment by chrisprice** [comment]
Thinking about it a little more, the identity check is really there to check whether the scale had changed since it was last used to project the data. As scales are mutable we can't identity check them. We also can't use the has been set trick we use in the webgl module because they are routinely set on each render. That leaves us with an explicit equality check, the implementation of which would be scale dependent.

**Comment by chrisprice** [comment]
I've put up a [PR](#1500) covering my proposed solution. I'd welcome any general comments here or specific ones on the PR.

**Comment by chrisprice** [comment]
It is now possible to work around this by specifying a custom scale mapper.
