### ISSUE TITLE
problem with d3.scaleTime when scaling the data inside webgl shader due to float32 precision

### ISSUE THREAD

**Issue by gosthell** [d3fc/d3fc#1491]
If the scaling of the timestamps is done in the shader, javascript dates are converted into millisecond timestamps, which are then passed into a Float32Array. This causes a rounding error due to float32 being unable to represent such big numbers accurately. I'm not sure there is any way around this, maybe force the scaling to be done outside the shader in scaleMapper.js..

**Comment by chrisprice** [comment]
You're correct, Float32 will only offer precise representation of +/- 2^24 ms which is about 9 hours. Larger values can be represented but as you say with reduced accuracy as the value increases due to floating-point rounding errors.

As discussed in #1490 if `scaleMapper` supported defining an arbitrary `{ scale, webglScale}` against an input scale, `scale` could be used to preprocess the values by translating them to be closer to 0 in the range of interest and truncating them to an suitable accuracy (assuming a suitable accuracy can be achieved for the required range when using a Float32). Would that work in your use-case?

**Comment by gosthell** [comment]
Yes that would help a lot !

**Comment by chrisprice** [comment]
Thinking about it a little more, the identity check is really there to check whether the scale had changed since it was last used to project the data. As scales are mutable we can't identity check them. We also can't use the has been set trick we use in the webgl module because they are routinely set on each render. That leaves us with an explicit equality check, the implementation of which would be scale dependent.

**Comment by gosthell** [comment]
I have resolved this issue using the decorate pattern for the ScaleMapper
```
const draw = seriesWebglPoint()
 .scaleMapper((scale) => {
          if (scale === draw.xScale()) {
            return {
              scale: scale.copy(),
              webglScale: webglScaleLinear().domain(scale.range())
            }
          } else {
            return {
              scale: identity,
              webglScale: webglScaleLinear().domain(scale.domain())
            }
          }
        })
```
