### ISSUE TITLE
Can't find streaming candlestick example

### ISSUE THREAD

**Issue by tredondo** [d3fc/d3fc#1531]
https://d3fc.io/ shows a nice streaming animated GIF at the bottom. Where can I find that example? I clicked on it but none of the examples on that examples page shows streaming.

**Comment by chrisprice** [comment]
That's actually a live chart, you could inspect the page to find the code for it. You can also find it [here](https://github.com/d3fc/d3fc/tree/master/packages/d3fc-site/src/examples/streaming) although we're in the middle of a big change location in how we manage the examples so that's likely to change shortly (hopefully to be more easily discoverable)

**Comment by melroy89** [comment]
Thanks for pointing us to the right location.

**DISCLAIMER:** This is not how you should do streaming data in D3! 

Checkout [better examples like this](https://github.com/finallyayo/realtime-d3-graph/blob/master/app.js).. Or some other [random streaming graph](https://bl.ocks.org/boeric/6a83de20f780b42fadb9). Both are not using D3FC, but it gives you the knowledge about how you should threat updates().

I mean this D3FC example I tried myself, and is very memory intensive for the browser. Not to mention you recreating the full graph over and over again.. :confounded: 

How to do it correctly with D3FC? Since it should only recalculate the x/y domains and repopulating the data. Like so: remove(),exit(),date(newdata), enter()).

@chrisprice  Plz fix this example? Split the graph construction part from the update() part of the code.

**Comment by chrisprice** [comment]
Thanks for the feedback. It's a very good point that, with the current
example design, it is very hard to discover this content but I believe this
is covered in the [README](
https://github.com/d3fc/d3fc/blob/master/examples/idempotent-streaming-chart/README.md)
for that example -

> This example shows how the idempotent nature of D3FC can be used (in the
> extreme case!) to render dynamic data without retaining any references. The
> basic principle is that the chart render function should be an idempotent
> transformation of the data. As a result, if the data changes the entire
> render function is re-evaluated.

> This is considered extreme because it can cause performance problems.
> Creating and destroying components on every render will cause a lot of
> memory churn. It also prevents the components from maintaining any internal
> caches or references. For the best performance, where possible retain
> references to components that are re-used on subsequent renders.

It is also really valuable feedback that we don't have a best practice
streaming example. The closest we currently have [demonstrates the opposite
end of the performance spectrum](https://github.com/d3fc/d3fc/pull/1513)
which hopefully reassures you that we do understand the best practice.
However, this is not an ideal example because it's not an example (!),
requires extending rather than using the library and is very specific to
the webgl API.

Thanks again for the feedback.

**Comment by melroy89** [comment]
Let me know if you have a correctly streaming example working, that I can use (eg. using chartCartesian), without recreating the whole chart and only updates the data sets. I think that means that we should migrate away from the `d3.select('#chart').call(chart)` method call.
