### ISSUE TITLE
latest version of d3fc is incompatible with D3v6

### ISSUE THREAD

**Issue by mortezae** [d3fc/d3fc#1606]
With new d3 version (6.0.0) release, examples under https://d3fc.io/examples/ stopped working as didn't specify the version of d3 to use from unpkg

**Comment by artemiusgreat** [comment]
Actually, some of them work, some don't... 

WebGL candlesticks works 
https://d3fc.io/examples/series-webgl-candlestick/

Canvas crosshair works
https://d3fc.io/examples/annotation-canvas-crosshair/ 

Ordinal doesn't work 
https://d3fc.io/examples/chart-cartesian-ordinal/

Simple candlestick chart doesn't work
https://d3fc.io/examples/simple-chart/

The error in the browser's console 
```
Uncaught TypeError: webglDataJoin(...).attr(...).classed is not a function
    at HTMLDivElement.<anonymous> (d3fc.js:9202)
    at Selection.selection_each [as each] (d3.js:1504)
    at cartesian (d3fc.js:9196)
    at Selection.selection_call [as call] (d3.js:1470)
    at index.js:19
```

Also, tried various combinations and versions from this CDN, no luck. 
https://www.cdnpkg.com/d3fc

**Comment by artemiusgreat** [comment]
Locally created bundle that I downloaded from github maybe a week ago works fine

**Comment by ColinEberhardt** [comment]
see #1605

**Comment by ColinEberhardt** [comment]
thanks for raising @mortezae - we'll get this fixed!

**Comment by chrisprice** [comment]
Starting a list of fixes here. I'm going to keep editing this comment as I discover more. Some will be blockers others will be nice to have.
- [x] Use d3-selection's new `selectChild`/`selectChildren` in `dataJoin`
- [x] Fix broken check in `cartesianChart` due to [new `selection.selection()`](https://github.com/d3/d3-selection/issues/238)
[`selection => maybeTransition.selection ? ...`](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/src/cartesian.js#L47). Replacing with `maybeTransition.tween` works but feels ugly.
- [x] The above check is also in [`dataJoin`](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-data-join/src/dataJoin.js#L24), annotation, axis & series (search for `.selection`)
- [x] Use of the [removed d3-selection's event property](https://observablehq.com/@d3/d3v6-migration-guide#events) - use the new `event` argument
- [x] Use of the [removed d3-selection's i and nodes arguments](https://observablehq.com/@d3/d3v6-migration-guide#events) - replace with `event.currentTarget`.
- [x] Argument shuffling caused by the [removal of d3-selection's event property](https://observablehq.com/@d3/d3v6-migration-guide#events)
* [x] (There were others... see the commits on #1627 for the full list)
