### ISSUE TITLE
Width calculations using the autoBandwidth component are not re-evaluated when a chart is resized

### ISSUE THREAD

**Issue by TheOneWithTheWrench** [d3fc/d3fc#1664]
Hey d3fc.

I was wondering if there was any way of dynamically resizing stacked bars in their width using your SeriesWebglBar that is also performant?

I've already tried playing around with .bandwidth and .autoBandwidth, but I can't seem to get it to work when my xDomain changes. It works fine upon the first render but stays that way throughout brush movement.
I've seen other solutions where the bars were accessed directly in the code and then manually changed their HTML width. But this is not really an option here due to using Webgl/canvas. 

Currently working in Angular. Do you guys have any suggestions as to how/if this can be accomplished? 

      
```
    const xExtent = fc
        .extentDate()
        .accessors([d => d.Date])
        .pad([0, 0.1]);

    const yExtent = fc
        .extentLinear()
        .accessors([a => a.map(d => d[1])])
        .include([0]);

    this.xScale = d3
        .scaleTime()
        .domain(xExtent(this.chartData.series))

    this.yScale = d3
        .scaleLinear()
        .domain(yExtent(this.chartData.stackedSeries))
        .nice();

      this.webglBar = fc
        .autoBandwidth(fc.seriesWebglBar())
        .xScale(this.xScale)
        .yScale(this.yScale)
        .crossValue(d => d.data.Date)
        .mainValue(d => d[1])
        .baseValue(d => d[0])

    this.chart = fc
        .chartCartesian(this.xScale, this.yScale)
        .yLabel(this.chartLabel)
        .webglPlotArea(this.webglBar)
        .canvasPlotArea(gridline)
        .xTickSize(1)
        .yOrient('left');

    private updateGraphView(xDomain)
    {
      this.updateGraphOnXAxis(xDomain)
      this.updateGraphOnYAxis(xDomain)

      d3.select(this.chartContainer.nativeElement)
          .datum(this.chartData.series)
          .transition()
          .duration(300)
          .ease(d3.easeLinear)
          .call(this.chart);

      this.reRenderWebglMain(this.xScale, this.yScale, this.webglBar, this.chartData);
    }

    private updateGraphOnXAxis(xDomain)
    {
      this.xScale = d3
          .scaleTime()
          .domain(xDomain)

      this.chart.xDomain(xDomain);
    }

    private updateGraphOnYAxis(xDomain)
    {
        let yExtentTest = fc
        .extentLinear()
        .accessors([a => a.map(d => {if(d.data.Date >= xDomain[0] && d.data.Date <= xDomain[1]) return d[1]; return 0} )])
        .include([0]);

        let yDomain = yExtentTest(this.chartData.stackedSeries)
        this.chart.yDomain(yDomain);
    }
```

**Comment by ColinEberhardt** [comment]
Thanks for raising this - I think it has uncovered a couple of underlying issues. 

As you have mentioned dynamic resizing, I presume you would like to use the [autoBandwidth](https://github.com/d3fc/d3fc/tree/master/packages/d3fc-series#auto-bandwidth) component if possible? One issue I have spotted is that the bandwidth is only computed when the component is initially created. Therefore, if your chart resizes dynamically, the bandwidths will not update accordingly.

To fix you can handle the 'measure' event that the various d3fc elements expose in order to handle chart size changes. This can be achieved as show below by using decorate to locate the respective element.

~~~
const data = fc.randomGeometricBrownianMotion().steps(100)(1);

const extent = fc.extentLinear();

const xScale = d3.scaleLinear().domain([0, data.length - 1]);

const yScale = d3.scaleLinear().domain(extent(data));

const series = fc
    .seriesSvgBar()
    .crossValue((d, i) => i)
    .mainValue(d => d)
    .defined(() => true);

const chart = fc
    .chartCartesian(xScale, yScale)
    .svgPlotArea(series)
    .xTickSize(1)
    .yOrient('left')
    .decorate(sel => {
        sel.enter()
            .select('d3fc-svg')
            .on('measure.bandwidth', (event, d) => {
                const { width } = event.detail;
                series.bandwidth(width / 200);
            });
    });

d3.select('#chart')
    .datum(data)
    .call(chart);
~~~

You'll notice that this example uses SVG rather than WebGL. That is because when I tried this with the WebGL series it did not update based on bandwidth changes - I have a feeling it is caching something somewhere.

We'll look into it.

**Comment by chrisprice** [comment]
A couple of minor things -

* You shouldn't need the `.enter().select('d3fc-svg')` within the decorate function. `sel` is the top level `d3fc-group` element which supports the `measure` event. `.on(` is idempotent so calling it multiple times on a selection has no effect.
* The example should work fine with WebGL components (https://codepen.io/chrisprice/pen/wvzboGj). N.B. there's another possible optimisation to update the bandwidth with the maximum possible performance but it's not straightforward*.
 
*The lower-level webgl code doesn't know that you are setting the bandwidth to a single value for all bars. Instead it assumes you're setting one value per bar to be most flexible. You could work around this by creating your own implementation of `seriesWebglBar` to customise its use of `webglSeriesBar`. You'd need to directly reference [constantAttribute](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-webgl/src/buffer/constantAttribute.js) from the d3fc-webgl package and use it for [bandwidthAttribute](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-series/src/webgl/bar.js#L16). However, I'd really not recommend doing this unless you have a huge dataset and are only interested in updating the bandwidth.
