### ISSUE TITLE
how to update intrabar values in candles?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [d3fc/d3fc#1688]

**Comment by ColinEberhardt** [comment]
Hi @hp8wvvvgnj6asjm7 - you have opened approximatley 10 issues, each with very little context. Open source maintainers are happy to help people using their projects and libraries, but cannot give such detailed guidance. I'd suggest you try to address some of these questions yourself, then return at a later date when you have a more specific question, including the context of what you have tried in order to resolve the issues yourself.
