### ISSUE TITLE
d3fc-element depends on CustomEvent

### ISSUE THREAD

**Issue by Serg65s** [d3fc/d3fc#1694]
=d3fc-element depends on CustomEvent. Make sure that you load a polyfill in older browsers.=

The problem arises when executing code on the nodejs side. How to fix this?

**Comment by chrisprice** [comment]
Don't include d3fc-element when using node i.e. use the individual packages (@d3fc/d3fc-random-data) not the top level one (@d3fc/d3fc).

**Comment by Serg65s** [comment]
Thank you for help

**Comment by TakodaS** [comment]
This is not complete. `d3fc-chart` imports element and you get this issue again. Very annoying. I think this really should be a warning rather than an error.

EDIT: My problem resulted from server side rendering since d3fc-element cannot find certain DOM elements and believes it is running in a legacy browser. To fix this, I just turned ssr off in sveltekit for my page that used d3fc and it worked.
