### ISSUE TITLE
Documentation Guide

### ISSUE THREAD

**Issue by sandeep-kr-kgp** [d3fc/d3fc#1705]
Is there any place where one can see detailed documentation about d3fc's functionalities ? For eg what `crossValue` does and what arguments does it expect . If not then can we have a detailed documentation ? There are examples in the repo but the code is barely readable if one wants to modify the chart.

**Comment by chrisprice** [comment]
Have you reviewed https://github.com/d3fc/d3fc/blob/master/README.md#documentation?

**Comment by sandeep-kr-kgp** [comment]
I had not. Thanks for the link, bookmarked it. I guess it'd be better if there's a github page / website for the documentation.
Also is there any fiddle / codepen playground for the same?

**Comment by chrisprice** [comment]
We prefer having the documentation in the README.md files because there are a number of advantages to us as maintainers: single source of truth, locality to the changed code, works offline, simpler build process, etc.. 

You might be interested in the expanding set of TypeScript definitions (#590) and the ability to [play with the examples offline](https://github.com/d3fc/d3fc/tree/master/examples#viewing-the-examples).
