### ISSUE TITLE
Low Barrel example crosshair issue

### ISSUE THREAD

**Issue by WilliamJameson** [d3fc/d3fc#645]
In the low barrel example if you replace the volume chart with another candle chart the crosshair's horizontal line will plot on both charts as they share the same data. Ideally, only the chart that the mouse is on has a vertical and horizontal line, and other charts just have the vertical line. I replaced the volume chart on the d3fc.io page with a candle chart, here is the image of the issue.

![crosshairissue](https://cloud.githubusercontent.com/assets/15219588/10618321/2965e3ce-7724-11e5-8314-543d31d0e25b.PNG)

**Comment by ColinEberhardt** [comment]
That's an interesting one, I guess it only worked with the volume series because the two charts have different scales for their y axis? So the volume chart would have been rendering a horizontal line that was outside of the plot area.

it is quite a straightforward task to remove the horizontal line for the crosshairs via the decorate pattern. I'll check whether this is still an issue with the recent reimplemention by @chrisprice and have a go at fixing it.

**Comment by chrisprice** [comment]
@colineberhardt, you're right about hiding the horizontal lines on the
volume chart. In fact there should be any on the main chart either (nor
circle).

I almost fixed this when doing the changes after I realised how much the
example has now drifted from the one I "found inspiration in". However as
we were in the middle of a decision on styling I didn't want to put the
effort in until a decision was made.

**Comment by chrisprice** [comment]
Fixed by #999.
